[WIP] Draft a write-up of parallel eNKI preprocessing
datalad-handbook/book pull request #547
Opened 2020-07-03 15:16 UTC by adswa

TODO:
- merge at the end
- proofread and tweak

2020-07-13 09:33 UTC, adswa commented
Removed WIP label despite some yet missing pieces (see TODOs in main comment), but it is good to go for a rough review, @mih.

2020-07-13 13:07 UTC, mih commented
Is there a build of this PR somewhere on RTD?

2020-07-13 13:40 UTC, adswa commented
huh, good question... There should be, but I can't find one. I'll investigate

2020-07-13 13:54 UTC, adswa commented
No clue why the readthedocs test build isn't triggered. it works for other PRs, and I have just resynced the webhooks...

2020-07-13 14:29 UTC, adswa commented
the f***... PR build also showed up here now... not sure how, but its fixed!

2020-08-05 14:47 UTC, adswa commented
@mih I have finished the draft on eNKI processing. Feedback is welcome.

2020-10-16 07:07 UTC, mih requested changes
This look great as-is, but I nevertheless left a few remarks to tweak the message here and there, and highlight a few things that I personally consider also/more relevant.

Thx!

2020-10-16 07:07 UTC, mih commented on docs/beyond_basics/101-170-dataladrun.rst
> +   If a commit has more than two parents, if is affectionately called an "Octopus" merge.
s/if/it

2020-10-16 07:07 UTC, mih commented on docs/beyond_basics/101-170-dataladrun.rst
> +This merge conflict arose in the ``fmriprep`` subdataset an originated from the fact that each job generated a ``CITATION.md`` file with minimal individual changes.
Personally, I would mention that octopus cannot have conflicts, but that is also often no problem for per-sample processing.

That it doesn't work out of the box with fmriprep is a footnote in this context, and I would move the mention and explanation entirely into a findoutmore box.

2020-10-16 07:22 UTC, adswa commented on docs/beyond_basics/101-170-dataladrun.rst
> +In this particular computation, following the naming scheme and structure of fMRIpreps output directories, one subdataset is created for the `freesurfer <https://surfer.nmr.mgh.harvard.edu/>`_ result
ok

2020-10-16 08:49 UTC, adswa commented on docs/beyond_basics/101-170-dataladrun.rst
> +In this particular computation, following the naming scheme and structure of fMRIpreps output directories, one subdataset is created for the `freesurfer <https://surfer.nmr.mgh.harvard.edu/>`_ result
I read it again, its outlined in line 62: 

> The preprocessing results will encompass several TB and about half a million files, and will therefore need to be split into two result datasets.

I'll use it below as well.

2020-10-16 09:03 UTC, adswa commented on docs/beyond_basics/101-170-dataladrun.rst
> +
but checking out ID-specific branches would be necessary regardless of dataset. Without the subdatasets, the superdataset would need, them, wouldn't it?

2020-10-16 09:58 UTC, mih commented on docs/beyond_basics/101-170-dataladrun.rst
> +
Yes, indeed.

2020-10-16 09:59 UTC, mih commented on docs/beyond_basics/101-170-dataladrun.rst
> +In this particular computation, following the naming scheme and structure of fMRIpreps output directories, one subdataset is created for the `freesurfer <https://surfer.nmr.mgh.harvard.edu/>`_ result
Ah, ok. I think I read the start on readthedocs and it was an older version.

2020-10-19 14:38 UTC, closed without merging